name: CI
on: [push, pull_request]
jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest
    environment:
      name: dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js runtime
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup prereqs
        run: |
          npm install -g lerna
          npm install -g typescript
          npm install -g yarn
          yarn install
          lerna bootstrap

      - name: Create .env file
        run: |
          rm -rf ./packages/dapp/.env
          touch ./packages/dapp/.env
          cat > ./packages/dapp/.env << END
          FAST_REFRESH=true
          BROWSER=false
          HTTPS=true
          REACT_APP_LOG_LEVEL=debug
          REACT_APP_FILE_WEB3STORAGE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDBGOGNjZTA5YjlENjc5RjY4RUFhOWJhQTYxMGM2NDcyMWEzRjQ0OTUiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NDM4NDY0NTYzMzEsIm5hbWUiOiJPUkdJRF9URVN>
          REACT_APP_GOOGLE_API_KEY=AIzaSyANAKdIUm0EZJkKzcCBpq1ROzMlRbr0mN4
          REACT_APP_MODE=production
          REACT_APP_NETWORK_ID=77
          REACT_APP_NETWORK_PROVIDER=https://sokol.poa.network
          REACT_APP_CONTRACT_ADDRESS=0xAD4B90b5053F7382A1313812559E044219BAE523
          END

      - name: Build dapp
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          rm -rf ./docs
          mkdir -p ./docs
          cd ./packages/dapp/
          yarn ghpages

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './docs'
          production-branch: main
          production-deploy: true
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
